src/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, g, jsonify, session, request
from sqlalchemy import func
from .utils import login_required, club_access_required, login, logout
from forms import (
    UserAddForm,
    LoginForm,
)
from models import db, User


auth_route = Blueprint("auth_route", __name__)

@auth_route.route("/register", methods=["GET", "POST"])
def registration_view():
    """View function for new user registration"""

    registration_form = UserAddForm()
    if registration_form.validate_on_submit():
        new_user = User.signup(registration_form.data)
        if new_user:
            flash(f"Welcome {new_user.first_name} to the BookwormDen", "success")
            login(new_user)
            return redirect(url_for("den_route.user_den_view"))
        else:
            flash("Error creating new user, please try again", "danger")

    return render_template("user_signup.html", form=registration_form)


@auth_route.route("/login", methods=["GET", "POST"])
def login_view():
    """View function for user login"""
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user_attempt = (
            db.session.query(User)
            .filter(User.username == login_form.data["username"])
            .first()
        )
        if user_attempt and user_attempt.validate_user(login_form.data["password"]):
            login(user_attempt)
            flash(f"Welcome back {user_attempt.first_name}", "success")
            return redirect(url_for("den_route.user_den_view"))
        else:
            flash("User and/or password invalid, please try again", "danger")
    return render_template("user_login.html", form=login_form)


@auth_route.route("/logout", methods=["POST"])
def logout_view():
    """View function for user logout"""
    if g.user:
        logout()
    return redirect(url_for("homepage"))

src/routes/book.py
from flask import Blueprint, render_template, redirect, url_for, flash, g, jsonify, request, current_app
import requests
from operator import and_
from .utils import login_required, club_access_required, login, logout
from forms import (
    UserAddForm,
    LoginForm,
    UserEditForm
)
from models import db, Book, Comment, Club, ClubMembers, ClubBook

GOOGLE_BOOKS_API_URL = "https://www.googleapis.com/books/v1/volumes"

book_route = Blueprint("book_route", __name__)


@book_route.route("/search", methods=["GET"])
def books_search_route():
    """Route to execute book search queries. Replies with json file with search content"""
    title_search = request.args.get("q", "")
    if not title_search:
        return jsonify({"error": "Please enter a book title to search"}), 400
    api_key = current_app.config["GOOGLE_API_KEY"]
    params = {
        "q": f"intitle:{title_search}",
        "key": api_key,
        "maxResults": 40,
        "printType": "books",
        # "projection": "lite",
        "langRestrict": "en",
    }

    response = requests.get(url=GOOGLE_BOOKS_API_URL, params=params)
    if response.status_code == 200:
        data = response.json()
        books = []
        for item in data.get("items", []):
            if item["volumeInfo"]["language"] == "en":
                id = item.get("id")
                volume_info = item.get(
                    "volumeInfo", {}
                )  # volume is the google book term for an item (book, magazine or other content)
                data = {
                    "title": volume_info.get("title"),
                    "authors": volume_info.get("authors", []),
                    "publishedDate": volume_info.get("publishedDate"),
                    "description": volume_info.get("description"),
                    "thumbnail": volume_info.get("imageLinks", {}).get("thumbnail"),
                    "id": id,
                }
                books.append({"data": data})

        return jsonify(books)
    else:
        return jsonify(
            {"error": "Failed to fetch data please try again"}
        ), response.status_code


@book_route.route("/book/<volume_id>", methods=["GET"])
def book_details_route(volume_id):
    """Route to collect detailed information for a particular book volume"""
    api_key = current_app.config["GOOGLE_API_KEY"]
    params = {
        "key": api_key,
    }

    response = requests.get(url=f"{GOOGLE_BOOKS_API_URL}/{volume_id}", params=params)
    if response.status_code == 200:
        data = response.json()
        volume_info = data.get(
            "volumeInfo", {}
        )  # volume is the google book term for an item (book, magazine or other content)
        book_data = {
            "title": volume_info.get("title", ""),
            "authors": volume_info.get("authors", []),
            "categories": volume_info.get("categories", []),
            "publisher": volume_info.get("publisher", ""),
            "publishedDate": volume_info.get("publishedDate"),
            "description": volume_info.get("description", ""),
            "thumbnail": volume_info.get("imageLinks", {}).get("thumbnail"),
            "page_count": volume_info.get("pageCount", 0),
            "average_rating": volume_info.get("averageRating", 0),
            "id": volume_id,
        }
        return jsonify(book_data)
    else:
        return jsonify(
            {"error": "Failed to fetch data please try again"}
        ), response.status_code


@book_route.route("/book/<volume_id>/clubs", methods=["GET"])
@login_required
def book_club_reading_list(volume_id):
    """Route to collect the reading clubs from a the connected user and if the given book is already in the reading list"""
    book = db.get_or_404(Book, volume_id)
    user_member_clubs = [
        membership.club
        for membership in g.user.membership
        if membership.status in [1, 2]
    ]
    included_clubs = [club.name for club in user_member_clubs if club in book.clubs]
    club_choices = [club.name for club in user_member_clubs if club not in book.clubs]

    return jsonify(included=included_clubs, choices=club_choices)


@book_route.route("/book/<volume_id>/add", methods=["POST"])
@login_required
def add_book_club_reading_list(volume_id):
    """Route to add a book to the reading club book list"""
    json_data = request.get_json()
    club_name = json_data.get("club_name")
    book = db.get_or_404(Book, volume_id)
    club = db.session.query(Club).filter(Club.name == club_name).first()
    added = club.add_book_to_list(book)
    if added:
        data = {"book": book.title, "club": club.name}
        return jsonify(added=data), 200
    else:
        return jsonify(json_data), 400


@book_route.route("/book/<volume_id>/delete", methods=["POST"])
@login_required
def remove_book_club_reading_list(volume_id):
    """Route to remove a book from the reading club book list"""
    json_data = request.get_json()
    club_id = json_data.get("club_id")
    club = db.get_or_404(Club, club_id)
    book = db.get_or_404(Book, volume_id)
    owner = (
        db.session.query(ClubMembers)
        .filter(and_(ClubMembers.club_id == club_id, ClubMembers.status == 1))
        .first()
    )
    if owner.member_id == g.user.id:
        book_list = db.get_or_404(ClubBook, (club_id, volume_id))
        deleted = book_list.delete()
        if deleted:
            data = {"book": book.title, "club": club.name}
            return jsonify(deleted=data), 200
        else:
            return jsonify(json_data), 400
    else:
        return jsonify(json_data), 500


"""
Book Comments Route
"""


@book_route.route("/comments/<volume_id>", methods=["GET"])
@login_required
def book_comments_route(volume_id):
    """Route to read all available comments from a given book. Replies with json file with comments array"""
    comments = (
        db.session.query(Comment)
        .order_by(Comment.date)
        .filter(and_(Comment.book_id == volume_id, Comment.domain == 2))
        .all()
    )
    if not comments:
        return jsonify({"error": "No comments found in the database"}), 400

    return jsonify(comments=[book_comment.serialize() for book_comment in comments])

src/routes/club.py
from flask import Blueprint, render_template, redirect, url_for, flash, g, jsonify, request
from .utils import login_required, club_access_required, login, logout
from forms import NewClubForm
from models import db, Club, ClubMembers, User


club_route = Blueprint("club_route", __name__)

@club_route.route("/", methods=["GET", "POST"])
@login_required
def clubs_view():
    """View function to open user book clubs home"""

    club_form = NewClubForm()
    if request.method == "POST" and club_form.validate_on_submit():
        new_club = Club.create_club(
            name=club_form.name.data,
            description=club_form.description.data,
            owner_id=g.user.id,
        )
        if new_club:
            flash("Reading club added to the database", "success")
        else:
            flash("Error adding the reading club, please try again", "danger")
        return redirect(url_for("club_route.clubs_view"))
    clubs_member = [
        membership.club for membership in g.user.membership if membership.status == 2
    ]
    clubs_owner = [
        membership.club for membership in g.user.membership if membership.status == 1
    ]
    clubs_invited = [
        membership.club for membership in g.user.membership if membership.status == 3
    ]
    return render_template(
        "clubs_page.html",
        form=club_form,
        owned=clubs_owner,
        member=clubs_member,
        invited=clubs_invited,
    )


@club_route.route("/<club_id>", methods=["GET"])
@login_required
@club_access_required
def club_view(club_id):
    """View function to open book club information"""
    club = db.get_or_404(Club, club_id)
    owner = next(
        (member.user for member in club.membership if member.status == 1), None
    )
    memberships = (
        db.session.query(ClubMembers)
        .filter(ClubMembers.club_id == club_id)
        .order_by(ClubMembers.status)
    )

    return render_template("club.html", club=club, memberships=memberships, owner=owner)


@club_route.route("/<club_id>/edit", methods=["GET", "POST"])
@login_required
def edit_club_view(club_id):
    """View function to edit user book information"""
    club = db.get_or_404(Club, club_id)
    club_form = NewClubForm(obj=club, current_name=club.name)
    if request.method == "POST" and club_form.validate_on_submit():
        updated_club = club.update(
            name=club_form.name.data,
            description=club_form.description.data,
        )
        if updated_club:
            flash("Reading club updated", "success")
        else:
            flash("Error updating the reading club, please try again", "danger")
        return redirect(url_for("club_route.edit_club_view", club_id=club_id))
    return render_template("edit_club_page.html", form=club_form, club_id=club_id)


@club_route.route("/delete", methods=["POST"])
@login_required
def delete_club_route():
    """View function to edit user book information"""
    club_id = request.form["club_id"]
    club = db.get_or_404(Club, club_id)
    deleted = club.delete()
    if deleted:
        flash("Club deleted", "success")
    else:
        flash("Error deleting the reading club, please try again", "danger")
    return redirect(url_for("club_route.clubs_view"))


@club_route.route("/<club_id>/add", methods=["POST"])
@login_required
def add_user_route(club_id):
    """Route to add a member to a reading club"""
    json_data = request.get_json()
    user = db.session.query(User).filter(User.username == json_data["username"]).first()
    if user:
        new_membership = ClubMembers.enrol_user(
            club_id=club_id, member_id=user.id, status=3
        )
    else:
        new_membership = False
    if new_membership:
        data = {
            "first_name": user.first_name,
            "last_name": user.last_name,
        }
        return jsonify(added_member=data), 200
    else:
        return jsonify(json_data), 400


@club_route.route("/<club_id>/delete", methods=["POST"])
@login_required
def delete_user_route(club_id):
    """Route to add a member to a reading club"""
    json_data = request.get_json()
    user = db.session.query(User).filter(User.username == json_data["username"]).first()
    membership = db.get_or_404(ClubMembers, (club_id, user.id))
    delete = membership.delete()
    if delete:
        data = {
            "first_name": user.first_name,
            "last_name": user.last_name,
        }
        return jsonify(removed_member=data), 200
    else:
        return jsonify(json_data), 400


@club_route.route("/<club_id>/invite", methods=["POST"])
@login_required
def process_invite_route(club_id):
    """Route to process a reading club invitation, either accept or reject"""
    response = request.form.get("invite")
    membership = db.get_or_404(ClubMembers, (club_id, g.user.id))
    if response == "accept":
        accept = membership.accept_invite()
        if accept:
            flash(f"You joined {membership.club.name}", "success")
        else:
            flash("Error processing your response, please try again", "danger")

    if response == "reject":
        reject = membership.reject_invite()
        if reject:
            flash(f"You reject to join {membership.club.name}", "warning")
        else:
            flash("Error processing your response, please try again", "danger")
    return redirect(url_for("club_route.clubs_view"))

src/routes/den.py
from flask import Blueprint, render_template, redirect, url_for, flash, g, jsonify, request
from datetime import date
from .utils import login_required, club_access_required, login, logout
from forms import (
    ReadStatisticsForm,
    NewCommentForm
)
from models import db, Book, UserBook, Comment

den_route = Blueprint("den_route", __name__)


@den_route.route("/", methods=["GET"])
@login_required
def user_den_view():
    """View function to open user home den"""
    reading_log = g.user.readlog
    return render_template("den_page.html", list=reading_log)


@den_route.route("/add-book", methods=["POST"])
@login_required
def add_book_to_user():
    """View function to add a volume to the user reading list.
    If the book does not exist in the local database, this function will add it (to the database) before adding to the user reading list.
    """
    book_entry = db.session.get(Book, request.form["api_id"])
    if not book_entry:
        book_entry = Book.save_book(request.form)
    if book_entry in g.user.books:
        flash("Book already in your reading list", "danger")
    else:
        book_added = g.user.add_to_reading_list(book_entry)
        if book_added:
            flash("Book added to your reading list", "success")
        else:
            flash("Error adding book to your reading list", "danger")

    return redirect(url_for("den_route.user_den_view"))


@den_route.route("/<volume_id>/delete", methods=["POST"])
@login_required
def remove_book_from_user(volume_id):
    """View function to remove a volume from the user reading list.
    The book should remain in the database.
    """
    readlog = db.get_or_404(UserBook, (g.user.id, volume_id))
    deleted = readlog.delete()
    if deleted:
        flash("Book removed from your reading list", "success")
    else:
        flash("Error removing the book, please try again", "danger")
    return redirect(url_for("den_route.user_den_view"))


@den_route.route("/<volume_id>", methods=["GET", "POST"])
@login_required
def book_view(volume_id):
    """View function to open book details and user information"""
    readlog = db.session.query(UserBook).filter_by(user_id=g.user.id, book_id=volume_id).first()
    if not readlog:
        flash("Book not added to your den, add it first", "danger")
        return redirect(request.referrer or url_for("den_route.user_den_view"))
    stat_form = ReadStatisticsForm(obj=readlog)
    user_comment = db.session.get(Comment, (g.user.id, volume_id))
    comment_form = NewCommentForm(obj=user_comment)

    if (
        request.method == "POST"
        and stat_form.validate_on_submit()
        and request.form.get("submit") == "statform"
    ):
        updated = readlog.update_info(stat_form.data)
        if updated:
            flash("Information updated", "success")
        else:
            flash("Error updating information, please try again", "success")
        return redirect(url_for("den_route.book_view", volume_id=volume_id))
    if (
        request.method == "POST"
        and comment_form.validate_on_submit()
        and request.form.get("submit") == "commentform"
    ):
        if user_comment:
            updated = user_comment.update(comment_form.data)
            if updated:
                flash("Comment updated successfully", "success")
            else:
                flash("Error updating your comment", "danger")
            return redirect(url_for("den_route.book_view", volume_id=volume_id))
        else:
            new_comment_data = {
                **comment_form.data,
                "user_id": g.user.id,
                "book_id": volume_id,
                "date": date.today(),
            }
            new_comment = Comment.create_comment(new_comment_data)
            if new_comment:
                flash("Comment added successfully", "success")
            else:
                flash("Error adding your comment", "danger")
            return redirect(url_for("den_route.book_view", volume_id=volume_id))

    book_data = db.get_or_404(Book, volume_id)
    return render_template(
        "book.html",
        book=book_data,
        statform=stat_form,
        commentform=comment_form,
    )

src/templates/book.html
{% extends 'base.html' %} {% block title %} Book Details {% endblock %} {% block
body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-lg-2 img-fluid">
            <div class="row">
                <img src="{{book.cover}}" />
            </div>
        </div>
        <div class="col-10">
            <div class="row">
                <div class="col-12 h4">
                    <strong>{{book.title}}</strong>
                </div>
            </div>
            <div class="row">
                <div class="col-4">{{book.authors}}</div>
            </div>
            <div class="row">
                <div class="col-4">Total {{book.page_count}} pages</div>
            </div>

            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                    <p
                        class="nav-link active"
                        aria-current="book description"
                        id="book-description"
                    >
                        Description
                    </p>
                </li>
                <li class="nav-item">
                    <p class="nav-link" id="book-statistics">Statistics</p>
                </li>
                <li class="nav-item">
                    <p
                        class="nav-link"
                        data-book="{{book.api_id}}"
                        id="book-comments"
                    >
                        Public Comments
                    </p>
                </li>
                <li class="nav-item">
                    <p
                        class="nav-link"
                        data-book="{{book.api_id}}"
                        id="book-add-comment"
                    >
                        Add comment
                    </p>
                </li>
                <li class="nav-item">
                    <p
                        class="nav-link"
                        data-book="{{book.api_id}}"
                        id="book-clubs"
                    >
                        Reading Clubs
                    </p>
                </li>
            </ul>
            <div id="div-description">
                <div class="row mt-3">
                    <div class="col-12">
                        <small> {{book.description | safe}} </small>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <small>
                            <strong> Categories : </strong> {{book.categories}}
                        </small>
                    </div>
                </div>
            </div>

            <div id="div-statistics" hidden>
                <form method="POST">
                    {{ statform.hidden_tag() }} {% for field in statform if
                    field.widget.input_type != 'hidden'%}
                    <div class="row">
                        <div class="col-7">{{field.label}}</div>
                        <div class="col-5">
                            {{field}} {% for error in field.errors %}
                            <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    {%endfor%}
                    <div class="edit-btn-area">
                        <button
                            type="submit"
                            name="submit"
                            value="statform"
                            class="btn btn-success w-100 mt-3"
                        >
                            Save
                        </button>
                    </div>
                </form>
                <form
                    method="post"
                    action="{{url_for('den_route.remove_book_from_user', volume_id = book.api_id)}}"
                >
                    <button type="submit" class="btn btn-danger w-100 mt-3">
                        Remove book from my Den
                    </button>
                </form>
            </div>
            <div id="div-comments" hidden>
                <ul id="ul-comments" class="list-group list-group-flush"></ul>
            </div>
            <div id="div-add-comment" hidden>
                <form method="POST">
                    {{ commentform.hidden_tag() }} {% for field in commentform
                    if field.widget.input_type != 'hidden'%}
                    <div class="row justify-content-center text-center">
                        <div class="col-12 col-lg-4">{{field.label}}</div>
                        <div class="col-12 col-lg-8">
                            {{field(class="m-2")}} {% for error in field.errors
                            %}
                            <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    {%endfor%}
                    <div class="edit-btn-area">
                        <button
                            type="submit"
                            name="submit"
                            value="commentform"
                            class="btn btn-success w-100 mt-3"
                        >
                            Save
                        </button>
                    </div>
                </form>
            </div>
            <div id="div-book-clubs" hidden>
                <ul id="ul-clubs" class="list-group list-group-flush"></ul>
                <select id="club-select-list" class="form-select m-4"></select>
                <p
                    class="btn btn-outline-secondary"
                    id="add-reading-club"
                    data-book="{{book.api_id}}"
                >
                    Add to reading Club
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/book.js"></script>
{% endblock %}

src/templates/club_edit_page.html
{% extends 'base.html' %} {% block title %} Edit Club Information {% endblock %}
{% block body %}

<p class="h2 text-center">Edit Reading Club Information</p>

<div id="add-club-form" class="container">
    <form
        method="POST"
        action="{{url_for('edit_club_view', club_id = club_id)}}"
    >
        {{ form.hidden_tag() }} {% for field in form if field.widget.input_type
        != 'hidden'%}
        <div>{{field.label(class="form-label")}}</div>
        <div>
            {{field(class="form-control")}} {% for error in field.errors %}
            <span class="form-text text-danger" data-error>{{error}}</span>
            {% endfor %}
        </div>
        {%endfor%}
        <div class="row">
            <div class="m-3 col">
                <button type="submit" class="btn btn-primary w-100">
                    Update
                </button>
            </div>
        </div>
    </form>
    <form method="post" action="{{url_for('delete_club_route')}}">
        <div class="m-3 col">
            <input type="hidden" name="club_id" value="{{club_id}}" />
            <button type="submit" class="btn btn-danger w-100">
                Delete Club
            </button>
        </div>
    </form>
</div>

{% endblock %}

src/templates/clubs_page.html
{% extends 'base.html' %} {% block title %} User Book Clubs {% endblock %} {%
block body %}

<h1>My Book Clubs</h1>
<div class="row container">
    <div class="col-12">Owner</div>
    <div class="col-12">
        <div class="row">
            {%for club in owned%}
            <div class="card col-12 col-sm-6 col-lg-4">
                <h5 class="card-header">{{club.name}}</h5>
                <div class="card-body">
                    <p class="card-text">{{club.description}}</p>
                    <a href="/clubs/{{club.id}}" class="btn btn-primary"
                        >View Club</a
                    >
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
<hr />
<div class="row container">
    <div class="col-12">Member</div>
    <div class="col-12">
        <div class="row">
            {%for club in member%}
            <div class="card col-12 col-sm-6 col-lg-4">
                <h5 class="card-header">{{club.name}}</h5>
                <div class="card-body">
                    <p class="card-text">{{club.description}}</p>
                    <a href="/clubs/{{club.id}}" class="btn btn-primary"
                        >View Club</a
                    >
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
<hr />
<div class="row container">
    <div class="col-12">Pending Invites</div>
    <div class="col-12">
        <div class="row">
            {%for club in invited%}
            <div class="card col-12 col-sm-6 col-lg-4">
                <h5 class="card-header">{{club.name}}</h5>
                <div class="card-body">
                    <p class="card-text">{{club.description}}</p>
                    <form
                        method="POST"
                        action="{{url_for('club_route.process_invite_route', club_id = club.id)}}"
                    >
                        <button
                            type="submit"
                            name="invite"
                            value="accept"
                            class="btn btn-success"
                        >
                            Join
                        </button>
                        <button
                            type="submit"
                            name="invite"
                            value="reject"
                            class="btn btn-danger"
                        >
                            Reject
                        </button>
                    </form>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
<hr />
<button class="btn btn-outline-secondary m-2 w-100" id="add-club-btn">
    Add New Club
</button>
<div id="add-club-form" class="container" hidden>
    <p class="h4 text-center">Create a new reading club</p>
    <form method="POST" action="{{url_for('club_route.clubs_view')}}">
        {{ form.hidden_tag() }} {% for field in form if field.widget.input_type
        != 'hidden'%}
        <div>{{field.label(class="form-label")}}</div>
        <div>
            {{field(class="form-control")}} {% for error in field.errors %}
            <span class="form-text text-danger" data-error>{{error}}</span>
            {% endfor %}
        </div>
        {%endfor%}
        <div class="m-3">
            <button type="submit" class="btn btn-success w-100">Create</button>
        </div>
    </form>
</div>
<script src="/static/clubs_page.js"></script>
{% endblock %}

src/templates/edit_club_page.html
{% extends 'base.html' %} {% block title %} Edit Club Information {% endblock %}
{% block body %}

<p class="h2 text-center">Edit Reading Club Information</p>

<div id="add-club-form" class="container">
    <form
        method="POST"
        action="{{url_for('club_route.edit_club_view', club_id = club_id)}}"
    >
        {{ form.hidden_tag() }} {% for field in form if field.widget.input_type
        != 'hidden'%}
        <div>{{field.label(class="form-label")}}</div>
        <div>
            {{field(class="form-control")}} {% for error in field.errors %}
            <span class="form-text text-danger" data-error>{{error}}</span>
            {% endfor %}
        </div>
        {%endfor%}
        <div class="row">
            <div class="m-3 col">
                <button type="submit" class="btn btn-primary w-100">
                    Update
                </button>
            </div>
        </div>
    </form>
    <form method="post" action="{{url_for('club_route.delete_club_route')}}">
        <div class="m-3 col">
            <input type="hidden" name="club_id" value="{{club_id}}" />
            <button type="submit" class="btn btn-danger w-100">
                Delete Club
            </button>
        </div>
    </form>
</div>

{% endblock %}

src/templates/homepage.html
{% extends 'base.html' %} {% block title %} The Book Worm Den {% endblock %} {%
block body %}

<div class="container mt-5">
    <div class="p-3 mb-3 bg-body-tertiary rounded-3">
        <div class="container-fluid">
            <div class="col-12 h1 text-center">
                <strong>Welcome to the Bookworm Den</strong>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-8 h4 m-3">
                Where book passionate people get together
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    This portal was designed as an educational project to allow people to search
    for book and record their reading adventures, also allowing friends and
    family to get together and share their passion for books by creating reading
    clubs.
</div>

<hr />
{%if not g.user%}
<div class="container text-center">
    Create your account today and start recording your adventure.
    <a
        href="{{url_for('auth_route.registration_view')}}"
        class="btn btn-primary w-100 mt-5 mb-5"
        >Sign-up</a
    >
    Returning user, please login to your account.
    <a
        href="{{url_for('auth_route.login_view')}}"
        class="btn btn-secondary w-100 mt-2"
        >Log-In</a
    >
</div>
{%endif%} {% endblock %}